#!/bin/bash
expected="$1"
input="$2"

./yacc "$input" > tmp.s
gcc -o tmp tmp.s
./tmp
actual="$?"

if [ "$actual" != "$expected" ]; then
    echo "$expected expected for input $input, but got $actual"
    exit 1
fi